---
name: Alien-IE7
version: 0.9.2
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: installing and finding IE7 JS compatibility library
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  Archive::Zip: 0
  Test::Exception: 0
provides:
  Alien::IE7:
    file: lib/Alien/IE7.pm
    version: 0.9.2
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
